### ISSUE TITLE
Language selector padding

### ISSUE THREAD

**Issue by ivanhercaz** [SemanticMediaWiki/Stragula#13]
Hi @kghbln!
I don't know if the Stragula skin what is available in semantic-mediawiki.org is the same that this repository, but using it I checked some detail that could be solved with one detail. I tried to fork and use Stragula in my own SMW installation, but it doesn't work:

> Whoops! The default skin for your wiki, defined in $wgDefaultSkin as chameleon, is not available.

But for this, I post another issue (#14).

About what I want to suggest, it is the non-alignment of the language selector in the menu. Check this screenshot:
![screenshot_20180306_235525](https://user-images.githubusercontent.com/8690921/37066715-965edb12-219e-11e8-9694-6a3a9dac4a13.png)

With developer tools I verified that it could be solved adding a `padding-left: 20px` to `#pt-uls`. Lines 318-320 in `stragula.less` could be something like this:
```less
#pt-uls {
	padding-left: 20px;
	a.uls-trigger {
		padding: 10px 0 10px 40px !important;
}
```

If I am not wrong, because I couldn't tested it in my local installation :(, it should work and result in this:
![screenshot_20180307_003504](https://user-images.githubusercontent.com/8690921/37066925-65da79e6-219f-11e8-8bce-1785b7421823.png)

Regards,
Iván

**Comment by ivanhercaz** [comment]
I closed this issue because I finally achieve to configure Stragula in my local installation, so I make a pull request (#15) to solve it. Excuse me for the annoyance.

**Comment by kghbln** [comment]
I saw this but was undecided if I should do the padding or not, so I did not since it was a unique element different to the rest. I however understand your rationale and this looks fine too. :)

**Comment by ivanhercaz** [comment]
I understand you, but maybe at this moment the snippet could solve the problem in the design. Until I understand, `#pt-uls` will be used just for this element, so it will be work without problems. The problem with this is the image that ULS added to the item.

**Comment by kghbln** [comment]
> The problem with this is the image that ULS added to the item.

It appears that they have changed the image. Thus we will have to tweak in June or July for the new version. This is when I will upgrade both the server and MediaWiki to newer versions.
