### ISSUE TITLE
Stragula is not available

### ISSUE THREAD

**Issue by ivanhercaz** [SemanticMediaWiki/Stragula#14]
Hi,
I tried to configure Stragula in my own local installation to test it and propose improvements and fixes errors that I find when I navigate through semantic-mediawiki.org. I made a fork and then I add the code of [LocalSettings.md](https://github.com/SemanticMediaWiki/Stragula/blob/master/LocalSettings.md) to my LocalSettings and load the skin.

At the first time I use `wfLoadSkin( 'Stragula' );` to load it, but it show me an error that then I solved thanks to cmln/chameleon#30. So I just use `$wgDefaultSkin = "Stragula";`, but now it shows me:
>`Whoops! The default skin for your wiki, defined in $wgDefaultSkin as chameleon, is not available.
...
If you have just upgraded MediaWiki:
MediaWiki 1.24 and newer no longer automatically enables installed skins (see Manual: Skin autodiscovery). You can paste the following lines into LocalSettings.php to enable all installed skins:
[blank line]
If you have just modified LocalSettings.php
Double-check the skin names for typos.`

I checked my LocalSettings to check if everything is fine, but I didn't find any error :/ 

Any idea? Thanks in advance!

**Comment by ivanhercaz** [comment]
This is my first time using a Chameleon-based skin. I wanted to test if Chameleon works fine for me to check if it was just a problem of Stragula or Chameleon. When I install Chameleon via Composer, I understand how works this skins :). And then, I realized that Stragula hasn't all the files of a skin, just the styles and schemas... So, I understand that for the use of Stragula I need to have in the skins folder both, Stragula and Chameleon, and then set in LocalSettings this Chameleon as default skin (`$wgDefaultSkin = "chameleon";`).

I'm not wrong and I understand fine the functioning of Chameleon-based skins, keep this issue closed. If not, I'm looking forward to the answer! Thanks in advance.

Regards,
Iván

**Comment by kghbln** [comment]
Stragula is indeed only a flavour so you have to install Chameleon first and set this optionally as your default skin. I have just improved the docu a bit to make this more obvious. Apart from that: No worries, it's my first time with Chameleon, too.

You can also use this on s-mw.o by selecting it via you personal preferences. I started doing so beginning of January. Hopefully I will be able to switch to this by default this month.

**Comment by ivanhercaz** [comment]
Thank you for your explanation, @kghbln! Now the docu is fine and explained, it is what I was going to recommend you. The only way to learn and improve our knowledge with this kinds of things is making and practicing, at least in my opinion of non-professional programmer.

And yes, I selected it in my preferences some days ago. If I find something more and I know how to do it, I will make a pull request, if not I will report an issue :+1:

**Comment by kghbln** [comment]
Yeah, perfection is always possible.

> If I find something more and I know how to do it, I will make a pull request, if not I will report an issue

That's the way!
